// Automatically generated by astro-icon
// 7795d500c9a39a94a104214e74438cb7699d7c199fb8ceb3fe89150809eed8fb

declare module "virtual:astro-icon" {
    export type Icon = "tabler/alert-triangle" | "tabler/bulb" | "tabler/flame" | "tabler/info";
}
