// Automatically generated by astro-icon
// e4b35c8d4d58abf3a66a03b002add46109c08612052a7f4586c4f30ab9a9010f

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "tabler/alert-triangle"
		| "tabler/bug"
		| "tabler/bulb"
		| "tabler/info";
}